/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as iensSol from "./IENS.sol";
export { IPhiMap__factory } from "./IPhiMap__factory";
export { IPhiObject__factory } from "./IPhiObject__factory";
export { IPhiRegistry__factory } from "./IPhiRegistry__factory";
