/* Autogenerated file. Do not edit manually. */

/* tslint:disable */

/* eslint-disable */
import type {
  IENS,
  IENSInterface,
} from "../../../../contracts/interfaces/IENS.sol/IENS";
import type { Provider } from "@ethersproject/providers";
import { Contract, Signer, utils } from "ethers";

const _abi = [
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "node",
        type: "bytes32",
      },
    ],
    name: "owner",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "node",
        type: "bytes32",
      },
    ],
    name: "resolver",
    outputs: [
      {
        internalType: "contract Resolver",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class IENS__factory {
  static readonly abi = _abi;
  static createInterface(): IENSInterface {
    return new utils.Interface(_abi) as IENSInterface;
  }
  static connect(address: string, signerOrProvider: Signer | Provider): IENS {
    return new Contract(address, _abi, signerOrProvider) as IENS;
  }
}
