/* Autogenerated file. Do not edit manually. */

/* tslint:disable */

/* eslint-disable */
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
} from "../common";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  BaseContract,
  BigNumber,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";

export interface ObjectControllerInterface extends utils.Interface {
  functions: {
    "setApproveForBasicObjects(address[])": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic: "setApproveForBasicObjects"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "setApproveForBasicObjects",
    values: [string[]]
  ): string;

  decodeFunctionResult(
    functionFragment: "setApproveForBasicObjects",
    data: BytesLike
  ): Result;

  events: {
    "SuccessApproveSet(address,address[])": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "SuccessApproveSet"): EventFragment;
}

export interface SuccessApproveSetEventObject {
  sender: string;
  addresses: string[];
}
export type SuccessApproveSetEvent = TypedEvent<
  [string, string[]],
  SuccessApproveSetEventObject
>;

export type SuccessApproveSetEventFilter =
  TypedEventFilter<SuccessApproveSetEvent>;

export interface ObjectController extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: ObjectControllerInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    setApproveForBasicObjects(
      addresses: string[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  setApproveForBasicObjects(
    addresses: string[],
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    setApproveForBasicObjects(
      addresses: string[],
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    "SuccessApproveSet(address,address[])"(
      sender?: string | null,
      addresses?: null
    ): SuccessApproveSetEventFilter;
    SuccessApproveSet(
      sender?: string | null,
      addresses?: null
    ): SuccessApproveSetEventFilter;
  };

  estimateGas: {
    setApproveForBasicObjects(
      addresses: string[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    setApproveForBasicObjects(
      addresses: string[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
