/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { FreeObject__factory } from "./FreeObject__factory";
export { PaidObject__factory } from "./PaidObject__factory";
export { PhiObject__factory } from "./PhiObject__factory";
export { SoulObject__factory } from "./SoulObject__factory";
