/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { FreeObject } from "./FreeObject";
export type { PhiObject } from "./PhiObject";
export type { PremiumObject } from "./PremiumObject";
